Base/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', TelemedicinaIndex.as_view(), name='telemedicina'),
    path('especialidades/', Especialidades.as_view(), name='especialidades'),
    path('list-especialidad/<slug:slug>/', ListEspecialistas.as_view(), name='list-especialidad'),

    # REGISTRO
    path('registro-especialista/', DoctorMultiStepForm.as_view(), name='registro-especialista'),

    path('index2/', Index2View.as_view(), name='index2'),
    path('index3/', Index3View.as_view(), name='index3',)

]

Clinicas/urls.py
from django.urls import path
from  .views import *

urlpatterns = [
    path('clinicas', ClinicasIndex.as_view(), name='clinicas'),
]

Doctores/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('doctores', DoctorIndex.as_view(), name='doctores'),
    path('new-doctores', DoctorNew.as_view(), name='new-doctores'),
    path('edit-doctores/<int:pk>', DoctorEdit.as_view(), name='edit-doctores'),

    #Especialidades
    
]

Pacientes/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('pacientes', PacientesIndex.as_view(), name='pacientes'),
]

Panel_Control/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('panel-general', PanelControlIndex.as_view(), name='panel-general')
]

TELEMEDICINA2025/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('Base.urls')),
    path('panel/', include('Panel_Control.urls')),
    path('pacientes/', include(('Pacientes.urls', 'pacientes'), namespace='pacientes')),
    path('clinicas/', include(('Clinicas.urls', 'clinicas'), namespace='clinicas')),
    path('doctores/', include(('Doctores.urls', 'doctores'), namespace='doctores')),
    path('admin/', admin.site.urls),
]   
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Panel_Control/models.py
from django.db import models

# Create your models here.

Panel_Control/views.py
from django.shortcuts import render
from django.views import generic


# Create your views here.
class PanelControlIndex(generic.TemplateView):
    template_name = 'panel-control/index.html'

Panel_Control/templates/panel-control/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <title>Sidebar 01</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="{% static 'css/style-generales.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{%  static 'css/style.css' %}">

</head>

<body>

    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
            <div class="p-4 pt-5">
                <a href="#" class="img logo rounded-circle mb-5" style="background-image: url(images/logo.jpg);"></a>
                <ul class="list-unstyled components mb-5">
                    <li>
                        <a href="#">Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'pacientes:pacientes' %}">Pacientes</a> <!--APARTADO DE PACIENTES --> 
                    </li>
                    <li>
                        <a href="{% url 'clinicas:clinicas' %}">Clinicas</a> <!--APARTADO DE CLINICAS --> 
                    </li>
                    <li>
                        <a href="{% url 'doctores:doctores' %}">Doctores</a> <!--APARTADO DE DCOTORES --> 
                    </li>
                </ul>

                <div class="footer">
                    <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template
                        is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com"
                            target="_blank">Colorlib.com</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>

            </div>
        </nav>

        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-5">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-primary">
                        <i class="fa fa-bars"></i>
                        <span class="sr-only">Toggle Menu</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fa fa-bars"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    </div>
                </div>
            </nav>
            {% block content %}{% endblock %}
        </div>
    </div>

    <script src="{% static  'js/jquery.min.js' %}"></script>
    <script src="{% static  'js/popper.js' %} "></script>
    <script src="{% static  'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>