Base/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', TelemedicinaIndex.as_view(), name='telemedicina'),
    path('especialidades/', Especialidades.as_view(), name='especialidades'),
    path('list-especialidad/<slug:slug>/', ListEspecialistas.as_view(), name='list-especialidad'),

    # REGISTRO
    path('registro-especialista/', DoctorMultiStepForm.as_view(), name='registro-especialista'),

    path('index2/', Index2View.as_view(), name='index2'),
    path('index3/', Index3View.as_view(), name='index3',)

]

Doctores/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('doctores', DoctorIndex.as_view(), name='doctores'),
    path('new-doctores', DoctorNew.as_view(), name='new-doctores'),
    path('edit-doctores/<int:pk>', DoctorEdit.as_view(), name='edit-doctores'),

    #Especialidades
    
]

TELEMEDICINA2025/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('Base.urls')),
    path('panel/', include('Panel_Control.urls')),
    path('pacientes/', include(('Pacientes.urls', 'pacientes'), namespace='pacientes')),
    path('clinicas/', include(('Clinicas.urls', 'clinicas'), namespace='clinicas')),
    path('doctores/', include(('Doctores.urls', 'doctores'), namespace='doctores')),
    path('admin/', admin.site.urls),
]   
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Doctores/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

class EspecialidadesModels(models.Model):
    nombre_especialidad  =  models.CharField(max_length=155)
    descripcion = models.TextField(blank=True, null=True)   
    codigo = models.CharField(max_length=10, unique=True)
    estado = models.BooleanField(default=True)
    slug = models.SlugField(unique=True, blank=True,) 

    class Meta:
        verbose_name = "Especialidad Médica"
        verbose_name_plural = "Especialidades Médicas"
        ordering = ['nombre_especialidad']
    
    def save(self, *args, **kwargs):
        # Generar el slug automáticamente basado en el nombre
        if not self.slug:
            self.slug = slugify(self.nombre_especialidad)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return self.nombre_especialidad


class DoctorModels(models.Model):
    picture =  models.ImageField(upload_to='Imagenes-Medicos')
    nombre_completo =  models.CharField(max_length=255)
    apellido  = models.CharField(max_length=255, null=True)
    tipo_documento = models.CharField(max_length=11, choices=[('DNI','DNI'), ('PASAPORTE', 'Pasaporte'),('CARNET EXT', 'Carnet de Extranjería')], default='DNI')
    numero_documento =  models.IntegerField(null=True)
    Genero = models.CharField(max_length=1, choices=[('M', 'Masculino'),('F', 'Femenino')], default='M')
    especialidad = models.ForeignKey('EspecialidadesModels', on_delete=models.CASCADE, null=True)
    cmp = models.IntegerField()
    experiencia = models.IntegerField()
    ciudad =  models.CharField(max_length=150)
    edad =  models.IntegerField()
    telefono =  models.IntegerField(null=123456789)
    correo_electronico =  models.CharField(max_length=255)
    estado =  models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Doctor'
        verbose_name_plural = 'Doctores'

Doctores/forms.py
from django import forms
from .models import *

class DoctorForms(forms.ModelForm):
    class Meta:
        model = DoctorModels
        fields = ['picture', 'nombre_completo', 'apellido','tipo_documento',
                   'numero_documento','Genero','especialidad',
                   'cmp', 'experiencia','ciudad', 'edad',
                    'telefono', 'correo_electronico', 'estado']
        widgets = {
            'nombre_completo': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_documento': forms.Select(attrs={'class': 'form-control'}),
            'numero_documento': forms.NumberInput(attrs={'class': 'form-control'}),
            'Genero': forms.Select(attrs={'class': 'form-control'}),
            'especialidad': forms.Select(attrs={'class': 'form-control'}),
            'cmp': forms.TextInput(attrs={'class': 'form-control'}),
            'experiencia': forms.NumberInput(attrs={'class': 'form-control'}),
            'ciudad': forms.TextInput(attrs={'class': 'form-control'}),
            'edad': forms.NumberInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'correo_electronico': forms.EmailInput(attrs={'class': 'form-control'}),
            'estado': forms.CheckboxInput(attrs={'class': 'form-control'}),
        }


class DoctorFormStep1(forms.ModelForm):
    class Meta:
        model = DoctorModels
        fields = ['picture', 'nombre_completo',  'apellido', 'tipo_documento',
                'numero_documento','Genero', 'especialidad','cmp']
        widgets = {
            'nombre_completo': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_documento': forms.Select(attrs={'class': 'form-control'}),
            'numero_documento': forms.NumberInput(attrs={'class': 'form-control'}),
            'Genero': forms.Select(attrs={'class': 'form-control'}),
            'especialidad': forms.Select(attrs={'class': 'form-control'}),
            'cmp': forms.TextInput(attrs={'class': 'form-control'}),
        }


class DoctorFormStep2(forms.ModelForm):
    class Meta:
        model = DoctorModels
        fields = ['experiencia','ciudad', 'edad',
                'telefono', 'correo_electronico', ]
        
        widgest = {
            'experiencia': forms.NumberInput(attrs={'class': 'form-control'}),
            'ciudad': forms.TextInput(attrs={'class': 'form-control'}),
            'edad': forms.NumberInput(attrs={'class': 'form-control'}),
            'telefono': forms.TextInput(attrs={'class': 'form-control'}),
            'correo_electronico': forms.EmailInput(attrs={'class': 'form-control'}),
        }

Doctores/views.py
from django.shortcuts import render
from django.views import generic
from .models import *
from .forms import *

from django.urls import reverse_lazy

# Create your views here.
class DoctorIndex(generic.ListView):
    model = DoctorModels
    context_object_name = 'doctores'
    template_name = 'doctores/index-doctores.html'

class DoctorNew(generic.CreateView):
    model = DoctorModels
    form_class = DoctorForms
    template_name = 'doctores/forms-doctores.html'
    success_url = reverse_lazy('doctores:doctores')

class DoctorEdit(generic.UpdateView):
    model = DoctorModels
    form_class = DoctorForms
    template_name = 'doctores/forms-doctores.html'
    success_url = reverse_lazy('doctores:doctores')

Doctores/templates/doctores/forms-doctores.html
{% extends 'panel-control/index.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    {{ form.as_p }}
    <button type="submit">Guardar Doctor</button>
</form>

{% endblock %}

Doctores/templates/doctores/index-doctores.html
{% extends 'panel-control/index.html' %}
{% block content %}
<div class="btn-add-001">
    <h4>Listado de Doctores</h4>
    <a href="{% url 'doctores:new-doctores' %}" class="btn btn-secondary">Nuevo Doctor</a>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Picture</th>
            <th scope="col">Nombre</th>

            <th scope="col">N° Colegiatura</th>
            <th scope="col">Correo Electrónico</th>
            <th scope="col">Estado</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for dc in doctores %}
        <tr>

            <td class="img-center"><img class="img-dc-picture" src="{{ dc.picture.url }}" alt=""></td>
            <td class="th-center">{{ dc.nombre_completo }}</td>
            <td class="th-center">{{ dc.especialidad.nombre_especialidad }}</td>
            <td class="th-center">{{ dc.cmp }}</td>
            <td class="th-center">{{ dc.correo_electronico }}</td>
            <td class="th-center">{{ dc.estado }}</td>
            <td class="th-center">
                <a href="{% url 'doctores:edit-doctores' dc.pk  %}" class="btn btn-warning"><i class="fa-solid fa-pencil"></i></a>
                <a href="" class="btn btn-danger"><i class="fa-solid fa-trash"></i></a>
            </td>

        </tr>
        {% endfor %}
    </tbody>
</table>


<!-- MODAL -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Guardar Doctor</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>



{% endblock %}